add wave -position instertpoint \
    sim:/tb/clk \
    sim:/tb/BIS_clk \
    sim:/tb/resetn \
    sim:/tb/BIS_addr \
    sim:/tb/BIS_rd \
    sim:/tb/BIS_rdata \
    sim:/tb/BIS_wr \
    sim:/tb/BIS_wdata \
    sim:/tb/s \
    sim:/tb/NF_coeffs \
    sim:/tb/crpa/NCH \
    sim:/tb/crpa/NT \
    sim:/tb/crpa/NBF \
    sim:/tb/crpa/NF_coeff_width \
    sim:/tb/crpa/BF_coeff_width \
    sim:/tb/crpa/NF_lsb_drop \
    sim:/tb/crpa/NF_coeffs \
    sim:/tb/crpa/NF_CH_coeffs \
    sim:/tb/crpa/BF_RE_coeffs \
    sim:/tb/crpa/BF_RE_CH_coeffs \
    sim:/tb/crpa/BF_IM_coeffs \
    sim:/tb/crpa/BF_IM_CH_coeffs \
    sim:/tb/crpa/BF_RE_out_full \
    sim:/tb/crpa/BF_IM_out_full \
    {sim:/tb/crpa/SIGMAG_BF[0]/sig_mag_RE/data_in} \
    {sim:/tb/crpa/SIGMAG_BF[0]/sig_mag_RE/por_res} \
    {sim:/tb/crpa/SIGMAG_BF[0]/sig_mag_RE/sig} \
    {sim:/tb/crpa/SIGMAG_BF[0]/sig_mag_RE/mag} \
    {sim:/tb/crpa/SIGMAG_BF[0]/sig_mag_RE/cntr_iter} \
    {sim:/tb/crpa/SIGMAG_BF[0]/sig_mag_RE/valid} \
    {sim:/tb/crpa/SIGMAG_BF[0]/sig_mag_RE/cntr} \
    {sim:/tb/crpa/SIGMAG_BF[0]/sig_mag_RE/mag_cntr} \
    {sim:/tb/crpa/SIGMAG_BF[0]/sig_mag_RE/mag_bisec} \
    {sim:/tb/crpa/SIGMAG_BF[0]/sig_mag_RE/resetn} \
    {sim:/tb/crpa/SIGMAG_BF[0]/sig_mag_RE/por_reg} \
    {sim:/tb/crpa/SIGMAG_BF[0]/sig_mag_RE/por_reg_a} \
    {sim:/tb/crpa/SIGMAG_BF[0]/sig_mag_RE/por_reg_b} \
    {sim:/tb/crpa/SIGMAG_BF[1]/sig_mag_RE/data_in} \
    {sim:/tb/crpa/SIGMAG_BF[1]/sig_mag_RE/por_res} \
    {sim:/tb/crpa/SIGMAG_BF[1]/sig_mag_RE/sig} \
    {sim:/tb/crpa/SIGMAG_BF[1]/sig_mag_RE/mag} \
    {sim:/tb/crpa/SIGMAG_BF[1]/sig_mag_RE/cntr_iter} \
    {sim:/tb/crpa/SIGMAG_BF[1]/sig_mag_RE/valid} \
    {sim:/tb/crpa/SIGMAG_BF[1]/sig_mag_RE/cntr} \
    {sim:/tb/crpa/SIGMAG_BF[1]/sig_mag_RE/mag_cntr} \
    {sim:/tb/crpa/SIGMAG_BF[1]/sig_mag_RE/mag_bisec} \
    {sim:/tb/crpa/SIGMAG_BF[1]/sig_mag_RE/resetn} \
    {sim:/tb/crpa/SIGMAG_BF[1]/sig_mag_RE/por_reg} \
    {sim:/tb/crpa/SIGMAG_BF[1]/sig_mag_RE/por_reg_a} \
    {sim:/tb/crpa/SIGMAG_BF[1]/sig_mag_RE/por_reg_b} \
    sim:/tb/crpa/CVM/MA/stat_cnt \
    sim:/tb/crpa/CVM/MA/NStat \
    sim:/tb/crpa/cvm_start \
    sim:/tb/crpa/CVM/start \
    sim:/tb/crpa/CVM/MA/start \
    sim:/tb/crpa/CVM/MA/ready \
    sim:/tb/crpa/CVM/ready \
    sim:/tb/crpa/cvm_ready \
    sim:/tb/CVM_ready \
    sim:/tb/crpa/REGS/CRPA_CONTROL \
    sim:/tb/crpa/REGS/CRPA_CONTROL_wr \
    sim:/tb/crpa/REGS/CRPA_STATUS \
    sim:/tb/crpa/REGS/CRPA_STATUS_rd \
    sim:/tb/crpa/REGS/BASE_ADDR \
    sim:/tb/crpa/REGS/CVM_BASE \
    sim:/tb/crpa/REGS/CVM_DATA_BASE \
    sim:/tb/crpa/REGS/addr \
    sim:/tb/crpa/REGS/CVM_addr \
    sim:/tb/crpa/REGS/CVM_rdata \
    sim:/tb/crpa/REGS/CVM_rd \
    sim:/tb/crpa/CVM/sel \
    sim:/tb/crpa/CVM/Y \
    sim:/tb/crpa/CVM/rd_addr \
    sim:/tb/crpa/CVM/MA/cell_addr \
    sim:/tb/crpa/CVM/rd_data \
    sim:/tb/crpa/CVM/MA/cell_data \
    sim:/tb/crpa/CVM/MA/macc_out \
    sim:/tb/crpa/CVM/MA/resetn \
    sim:/tb/crpa/CVM/MA/ena \
    sim:/tb/crpa/CVM/MA/start \
    sim:/tb/crpa/CVM/MA/ready \
    sim:/tb/crpa/CVM/MA/Sin \
    sim:/tb/crpa/CVM/MA/MACCS_NUM \
    {sim:/tb/crpa/CVM/MA/genblk1[0]/MCC/a} \
    {sim:/tb/crpa/CVM/MA/genblk1[0]/MCC/b} \
    {sim:/tb/crpa/CVM/MA/genblk1[0]/MCC/mult_reg} \
    {sim:/tb/crpa/CVM/MA/genblk1[0]/MCC/accum} \
    {sim:/tb/crpa/CVM/MA/genblk1[0]/MCC/accum_out} \
    {sim:/tb/crpa/CVM/MA/genblk1[0]/MCC/resetn} \
    {sim:/tb/crpa/CVM/MA/genblk1[0]/MCC/start} \
    {sim:/tb/crpa/CVM/MA/genblk1[0]/MCC/ena} \
    {sim:/tb/crpa/CVM/MA/genblk1[0]/MCC/ready} \
    {sim:/tb/crpa/CVM/MA/genblk1[1]/MCC/a} \
    {sim:/tb/crpa/CVM/MA/genblk1[1]/MCC/b} \
    {sim:/tb/crpa/CVM/MA/genblk1[1]/MCC/mult_reg} \
    {sim:/tb/crpa/CVM/MA/genblk1[1]/MCC/accum} \
    {sim:/tb/crpa/CVM/MA/genblk1[1]/MCC/accum_out} \
    {sim:/tb/crpa/CVM/MA/genblk1[1]/MCC/resetn} \
    {sim:/tb/crpa/CVM/MA/genblk1[1]/MCC/start} \
    {sim:/tb/crpa/CVM/MA/genblk1[1]/MCC/ena} \
    {sim:/tb/crpa/CVM/MA/genblk1[1]/MCC/ready} \
    sim:/tb/bf_out_re \
    sim:/tb/bf_out_im \
    sim:/tb/crpa/bf_re_sig \
    sim:/tb/crpa/bf_re_mag \
    sim:/tb/crpa/bf_im_sig \
    sim:/tb/crpa/bf_im_mag \
    sim:/tb/crpa/REGS/BF_RE_COEFF_IN \
    sim:/tb/crpa/REGS/BF_RE_COEFF 
