`define INTR_PERIOD_WIDTH 32

`define INTR_PULSE_DURATION_WIDTH 8

`define INTR_CNTL_OFFSET                BASE_ADDR + `ADDR_WIDTH'h0

`define INTR_PERIOD_OFFSET              BASE_ADDR + `ADDR_WIDTH'h1

`define INTR_DURATION_OFFSET            BASE_ADDR + `ADDR_WIDTH'h2

`define INTERRUPT_COUNTER_OFFSET        BASE_ADDR + `ADDR_WIDTH'h3

`define SAMPLE_COUNTH_OFFSET            BASE_ADDR + `ADDR_WIDTH'h4

`define SAMPLE_COUNTL_OFFSET            BASE_ADDR + `ADDR_WIDTH'h5

`define LAMP_OFFSET                     BASE_ADDR + `ADDR_WIDTH'h6

`define MEAN_OFFSET                     BASE_ADDR + `ADDR_WIDTH'h7

`define PLL_OFFSET                      BASE_ADDR + `ADDR_WIDTH'h8

`define COM_DO_INIT_OFFSET              BASE_ADDR + `ADDR_WIDTH'h10

`define COM_CODE_PHASE_INIT_OFFSET      BASE_ADDR + `ADDR_WIDTH'h11
`define COM_CODE_PHASE_OFFSET           BASE_ADDR + `ADDR_WIDTH'h11

`define COM_CHIP_AND_SYMB_INIT_OFFSET   BASE_ADDR + `ADDR_WIDTH'h12
`define COM_CHIP_AND_SYMB_OFFSET        BASE_ADDR + `ADDR_WIDTH'h12

`define COM_EPOCH_AND_TOW_INIT_OFFSET   BASE_ADDR + `ADDR_WIDTH'h13
`define COM_EPOCH_AND_TOW_OFFSET        BASE_ADDR + `ADDR_WIDTH'h13

`define COM_CHIP_MAX_OFFSET             BASE_ADDR + `ADDR_WIDTH'h14

`define COM_EPOCH_AND_SYMB_MAX_OFFSET   BASE_ADDR + `ADDR_WIDTH'h15

`define COM_EPOCH_INTR_OFFSET           BASE_ADDR + `ADDR_WIDTH'h16

`define COM_CODE_RATE_OFFSET            BASE_ADDR + `ADDR_WIDTH'h17

`define COM_CODE_PHASE_EXT_OFFSET       BASE_ADDR + `ADDR_WIDTH'h18

`define COM_CHIP_AND_SYMB_EXT_OFFSET    BASE_ADDR + `ADDR_WIDTH'h19

`define COM_EPOCH_AND_TOW_EXT_OFFSET    BASE_ADDR + `ADDR_WIDTH'h1a

`define COM_CODE_PHASE_CUR_OFFSET       BASE_ADDR + `ADDR_WIDTH'h1b

`define COM_CHIP_AND_SYMB_CUR_OFFSET    BASE_ADDR + `ADDR_WIDTH'h1c

`define COM_EPOCH_AND_TOW_CUR_OFFSET    BASE_ADDR + `ADDR_WIDTH'h1d

`define PPS_MAX_OFFSET                  BASE_ADDR + `ADDR_WIDTH'h1e

`define HIST_LOCK_OFFSET                BASE_ADDR + `ADDR_WIDTH'h1f

`define HIST_ADDR_OFFSET                BASE_ADDR + `ADDR_WIDTH'h20

`define HIST_DAT_OFFSET                 BASE_ADDR + `ADDR_WIDTH'h21