clc
clear
close all hidden

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: G:\tmp\a.csv
%
% Auto-generated by MATLAB on 14-Jul-2021 10:52:12

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["A_R", "A_I", "B_R", "B_I", "C_R", "C_I", "D_R", "D_I", "W_R", "W_I", "cut"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
a = readtable("G:\tmp\a.csv", opts);


%% Clear temporary variables
clear opts



%% test
N = length(a.cut);
dat = nan(2,N);

dat_fpga = [a.C_R+1i*a.C_I, a.D_R+1i*a.D_I].';

for i = 1:N
    dat(:,i)=butterfly([a.A_R(i)+1i*a.A_I(i),a.B_R(i)+1i*a.B_I(i)],a.W_R(i)+1i*a.W_I(i),2^3,a.cut(i),14);
    if(abs(sum(dat(i)-dat_fpga(i))))
        fprintf('i = %d, A_R=%d, A_I=%d, B_R=%d, B_I=%d, W_R=%d, W_I=%d, cut=%d\n',i,a.A_R(i),a.A_I(i),a.B_R(i),a.B_I(i),a.W_R(i),a.W_I(i),a.cut(i))
    end
end



error = abs(sum(sum(dat-dat_fpga)))/N;

if(error == 0)
    fprintf('ALL GOOD!\n')
else
    fprintf('ERROR! = %f\n',error)
end