`define ATT_ADDR_WIDTH					30

`define ATT_ID_OFFSET					BASE_ADDR + `ATT_ADDR_WIDTH'h00	
`define ATT_DATA_OFFSET					BASE_ADDR + `ATT_ADDR_WIDTH'h01		
`define ATT_CSMASK_OFFSET				BASE_ADDR + `ATT_ADDR_WIDTH'h02		
`define ATT_RESET_OFFSET				BASE_ADDR + `ATT_ADDR_WIDTH'h03	