#!/bin/bash
# Этот скрипт предназначен для создания нового документа
# Используются файлы-шаблоны Tmpl.tex и Tmpl_title.tex

res=0
# Запрос названия файла
while [ $res != "3" ]
do

    if [ $res == "0" -o $res == "1" ]
    then
	read -p "Введите название файла: " -e Name
    fi

    if [ -e "../$Name/$Name.tex" ]
    then
	echo Файл с названием \"Docs/$Name/$Name.tex\" уже существует
	break  # So ugly...
    fi

    if [ $res == "0" -o $res == "2" ]
    then
	read -p "Введите заголовок документа: " -e Title
    fi
    
    echo Имя файла: Docs/$Name/$Name.tex
    echo Заголовок: $Title

    echo Выберите:
    select ans in "  Создать файл" "  Исправить название файла" "  Исправить заголовок" "  Выход"
    do
	break
    done
    case "$ans" in
	"  Создать файл")
	    res=3
	    ;;
	"  Исправить название файла")
	    res=1
	    ;;
	"  Исправить заголовок")
	    res=2
	    ;;
	"  Выход")
	    break
    esac
done

# Каталог для документа
if [ ! -d "../$Name" ]; then mkdir "../$Name"; fi

# Подготовка Makefile
cp Makefile "../$Name"
cat ../MakefileLocal | sed "s/SUBDIRS=/SUBDIRS=$Name /g" > /tmp/tmp.file; mv /tmp/tmp.file ../MakefileLocal # Самому страшно

# Подготовка файла документа
cat Tmpl.tex | sed "s/Tmpl_title/$Name_title/g" > "../$Name/$Name.tex"

# Подготовка файла обрамления
cat Tmpl_title.tex | sed "s/Tmpl/$Name/g" > "../$Name/"$Name"_title.tex"


echo Файл \"Docs/$Name/$Name.tex\" создан
echo   Нужно добавить его в общий файл Docs/Impala_title.tex, иначе в сборный файл Impala.pdf он не попадёт.
echo   Дело это творческое, поэтому нужно делать руками.

