# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z045fbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/User/Desktop/misc-main/cometicus/prj/cometicus/cometicus.cache/wt [current_project]
set_property parent.project_path C:/Users/User/Desktop/misc-main/cometicus/prj/cometicus/cometicus.xpr [current_project]
set_property XPM_LIBRARIES {XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/User/Desktop/misc-main/cometicus/prj/cometicus/cometicus.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/board_param.v
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog/math.v
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/DDS_bin.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/interfaces/macro.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/DDS_sin_cos.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/time_scale_ch.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/bram_controller.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/facq_prn_ram.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/acq_ip.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/prestore.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/time_scale_com.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/max_args.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/fsm_controller.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/facq_prn_gen.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/debug/verilog_sv/data_collector.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/corr_ch.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/prn_gen.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/prn_ram.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/interfaces/dma.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog_sv/lim_cntr.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/imitator/verilog/imitator_channel.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/imitator/verilog/imitator.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog_sv/normalizer.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/irq_ctrl.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/debug/verilog_sv/rgb.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/calibration.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/trcv/trcv.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/ref_in_interpretator.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog_sv/vitdec.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/uart/rtl/axi_uart.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog_sv/decimator.svh
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog_sv/fir.svh
}
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/board_param.v]
set_property is_global_include true [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/board_param.v]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog/math.v]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/DDS_bin.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/interfaces/macro.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/DDS_sin_cos.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/time_scale_ch.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/bram_controller.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/facq_prn_ram.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/acq_ip.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/prestore.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/time_scale_com.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/max_args.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/fsm_controller.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/facq_prn_gen.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/debug/verilog_sv/data_collector.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/corr_ch.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/prn_gen.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/prn_ram.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/interfaces/dma.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog_sv/lim_cntr.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/imitator/verilog/imitator_channel.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/imitator/verilog/imitator.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog_sv/normalizer.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/irq_ctrl.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/debug/verilog_sv/rgb.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/calibration.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/trcv/trcv.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/ref_in_interpretator.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog_sv/vitdec.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/uart/rtl/axi_uart.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog_sv/decimator.svh]
set_property file_type "Verilog Header" [get_files C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog_sv/fir.svh]
read_verilog -library xil_defaultlib -sv {
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/DDS_bin.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/DDS_sin_cos.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/acq_IP.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/interfaces/adc_interf.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/interfaces/arm_interface.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/arr_accum.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/interfaces/axi3_interface.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/interfaces/axi3_to_inter.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/bram_controller.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/ch_mul.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/ch_mul_rom.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/sync/verilog/conv_reg.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/core.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/corr_ch.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/cpu_top.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/debug/verilog_sv/data_collector.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/sync/verilog/data_sync.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog_sv/dds_iq_hd.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/deserLTC217x.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/interfaces/dma.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/sync/verilog/ed_det.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/facq_prn_gen.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/facq_prn_ram.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog_sv/freq_counter.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/freq_shift.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/fsm_controller.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/interfaces/imi_interf.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/imitator/verilog/imitator.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/imitator/verilog/imitator_channel.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/interfaces/intbus_interf.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/irq_ctrl.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/sync/verilog/latency.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/sync/verilog/level_sync.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog_sv/lim_cntr.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog_sv/lim_qnt.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/max_args.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog_sv/max_parallel.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/mf.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog_sv/normalizer.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/prestore.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/prn_gen.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/prn_ram.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/acquisition/verilog_sv/quad.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/debug/verilog_sv/ram_block_sp.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog/randn/randn.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog/randn/randn_u.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/interfaces/regs_file.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/sync/verilog/reset_sync.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/debug/verilog_sv/rgb.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog_sv/sig_mag_v3.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/sync/verilog/signal_sync.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/time_scale_ch.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/correlator_new/verilog/time_scale_com.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/trcv/trcv.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog_sv/vitdec.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/imitator/verilog/wiper.sv
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/cometicus.sv
}
read_verilog -library xil_defaultlib {
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/global_param.v
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/debug/verilog/bram_block_v2.v
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/debug/verilog/bram_lut_v2.v
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog/piped_adder/piped_adder.v
  C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/dsp/verilog/piped_adder/piped_adder_stage.v
}
add_files C:/Users/User/Desktop/misc-main/cometicus/prj/cometicus/clonicus/zynq/zynq.bd
set_property used_in_implementation false [get_files -all c:/Users/User/Desktop/misc-main/cometicus/prj/cometicus/clonicus/zynq/ip/zynq_processing_system7_0_0_0/zynq_processing_system7_0_0_0.xdc]
set_property used_in_implementation false [get_files -all C:/Users/User/Desktop/misc-main/cometicus/prj/cometicus/clonicus/zynq/zynq_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top cometicus -part xc7z045fbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cometicus.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cometicus_utilization_synth.rpt -pb cometicus_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
