# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/User/Desktop/misc-main/cometicus/src/hdl/cometicus.xdc

# XDC: C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/uart/example/Arty/fpga/fpga.xdc

# XDC: C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/uart/example/NexysVideo/fpga/fpga.xdc

# XDC: C:/Users/User/Desktop/misc-main/cometicus/src/hdl/sub/uart/example/VCU108/fpga/fpga.xdc

# Block Designs: C:/Users/User/Desktop/misc-main/cometicus/prj/cometicus/clonicus/zynq/zynq.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq || ORIG_REF_NAME==zynq} -quiet] -quiet

# IP: c:/Users/User/Desktop/misc-main/cometicus/prj/cometicus/clonicus/zynq/ip/zynq_processing_system7_0_0_0/zynq_processing_system7_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_processing_system7_0_0_0 || ORIG_REF_NAME==zynq_processing_system7_0_0_0} -quiet] -quiet

# XDC: C:/Users/User/Desktop/misc-main/cometicus/prj/cometicus/clonicus/zynq/zynq_ooc.xdc
