######################################################################
#
# File name : cometicus_compile.do
# Created on: Wed Mar 20 10:22:54 +0300 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xilinx_vip
vlib modelsim_lib/msim/xil_defaultlib
vlib modelsim_lib/msim/xpm
vlib modelsim_lib/msim/axi_infrastructure_v1_1_0
vlib modelsim_lib/msim/smartconnect_v1_0
vlib modelsim_lib/msim/axi_protocol_checker_v2_0_2
vlib modelsim_lib/msim/axi_vip_v1_1_2
vlib modelsim_lib/msim/processing_system7_vip_v1_0_4

vmap xilinx_vip modelsim_lib/msim/xilinx_vip
vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
vmap xpm modelsim_lib/msim/xpm
vmap axi_infrastructure_v1_1_0 modelsim_lib/msim/axi_infrastructure_v1_1_0
vmap smartconnect_v1_0 modelsim_lib/msim/smartconnect_v1_0
vmap axi_protocol_checker_v2_0_2 modelsim_lib/msim/axi_protocol_checker_v2_0_2
vmap axi_vip_v1_1_2 modelsim_lib/msim/axi_vip_v1_1_2
vmap processing_system7_vip_v1_0_4 modelsim_lib/msim/processing_system7_vip_v1_0_4

vlog -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_2 -L axi_vip_v1_1_2 -L processing_system7_vip_v1_0_4 -L xil_defaultlib -L xilinx_vip -work xilinx_vip "C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/board_param.v" "C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/global_param.v" "+incdir+D:/Xlinx/Vivado/2018.1/data/xilinx_vip/include" \
"D:/Xlinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"D:/Xlinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"D:/Xlinx/Vivado/2018.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"D:/Xlinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"D:/Xlinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"D:/Xlinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"D:/Xlinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
"D:/Xlinx/Vivado/2018.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
"D:/Xlinx/Vivado/2018.1/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_2 -L axi_vip_v1_1_2 -L processing_system7_vip_v1_0_4 -L xil_defaultlib -L xilinx_vip -work xil_defaultlib "C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/board_param.v" "C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/global_param.v" "+incdir+../../../../clonicus/zynq/ipshared/ec67/hdl" "+incdir+../../../../clonicus/zynq/ipshared/02c8/hdl/verilog" "+incdir+../../../../clonicus/zynq/ipshared/b193/hdl" "+incdir+../../../../../../src/hdl/sub/dsp/verilog" "+incdir+../../../../../../src/hdl/sub/acquisition/verilog_sv" "+incdir+../../../../../../src/hdl/sub/interfaces" "+incdir+../../../../../../src/hdl/sub/correlator_new/verilog" "+incdir+../../../../../../src/hdl/sub/debug/verilog_sv" "+incdir+../../../../../../src/hdl/sub/dsp/verilog_sv" "+incdir+../../../../../../src/hdl/sub/imitator/verilog" "+incdir+../../../../../../src/hdl/trcv" "+incdir+../../../../../../src/hdl/sub/uart/rtl" "+incdir+D:/Xlinx/Vivado/2018.1/data/xilinx_vip/include" \
"D:/Xlinx/Vivado/2018.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"D:/Xlinx/Vivado/2018.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
"D:/Xlinx/Vivado/2018.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \

vcom -64 -93 -work xpm  \
"D:/Xlinx/Vivado/2018.1/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -64 -incr -work axi_infrastructure_v1_1_0 "C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/board_param.v" "C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/global_param.v" "+incdir+../../../../clonicus/zynq/ipshared/ec67/hdl" "+incdir+../../../../clonicus/zynq/ipshared/02c8/hdl/verilog" "+incdir+../../../../clonicus/zynq/ipshared/b193/hdl" "+incdir+../../../../../../src/hdl/sub/dsp/verilog" "+incdir+../../../../../../src/hdl/sub/acquisition/verilog_sv" "+incdir+../../../../../../src/hdl/sub/interfaces" "+incdir+../../../../../../src/hdl/sub/correlator_new/verilog" "+incdir+../../../../../../src/hdl/sub/debug/verilog_sv" "+incdir+../../../../../../src/hdl/sub/dsp/verilog_sv" "+incdir+../../../../../../src/hdl/sub/imitator/verilog" "+incdir+../../../../../../src/hdl/trcv" "+incdir+../../../../../../src/hdl/sub/uart/rtl" "+incdir+D:/Xlinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../clonicus/zynq/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_2 -L axi_vip_v1_1_2 -L processing_system7_vip_v1_0_4 -L xil_defaultlib -L xilinx_vip -work smartconnect_v1_0 "C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/board_param.v" "C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/global_param.v" "+incdir+../../../../clonicus/zynq/ipshared/ec67/hdl" "+incdir+../../../../clonicus/zynq/ipshared/02c8/hdl/verilog" "+incdir+../../../../clonicus/zynq/ipshared/b193/hdl" "+incdir+../../../../../../src/hdl/sub/dsp/verilog" "+incdir+../../../../../../src/hdl/sub/acquisition/verilog_sv" "+incdir+../../../../../../src/hdl/sub/interfaces" "+incdir+../../../../../../src/hdl/sub/correlator_new/verilog" "+incdir+../../../../../../src/hdl/sub/debug/verilog_sv" "+incdir+../../../../../../src/hdl/sub/dsp/verilog_sv" "+incdir+../../../../../../src/hdl/sub/imitator/verilog" "+incdir+../../../../../../src/hdl/trcv" "+incdir+../../../../../../src/hdl/sub/uart/rtl" "+incdir+D:/Xlinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../clonicus/zynq/ipshared/02c8/hdl/sc_util_v1_0_vl_rfs.sv" \

vlog -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_2 -L axi_vip_v1_1_2 -L processing_system7_vip_v1_0_4 -L xil_defaultlib -L xilinx_vip -work axi_protocol_checker_v2_0_2 "C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/board_param.v" "C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/global_param.v" "+incdir+../../../../clonicus/zynq/ipshared/ec67/hdl" "+incdir+../../../../clonicus/zynq/ipshared/02c8/hdl/verilog" "+incdir+../../../../clonicus/zynq/ipshared/b193/hdl" "+incdir+../../../../../../src/hdl/sub/dsp/verilog" "+incdir+../../../../../../src/hdl/sub/acquisition/verilog_sv" "+incdir+../../../../../../src/hdl/sub/interfaces" "+incdir+../../../../../../src/hdl/sub/correlator_new/verilog" "+incdir+../../../../../../src/hdl/sub/debug/verilog_sv" "+incdir+../../../../../../src/hdl/sub/dsp/verilog_sv" "+incdir+../../../../../../src/hdl/sub/imitator/verilog" "+incdir+../../../../../../src/hdl/trcv" "+incdir+../../../../../../src/hdl/sub/uart/rtl" "+incdir+D:/Xlinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../clonicus/zynq/ipshared/3755/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \

vlog -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_2 -L axi_vip_v1_1_2 -L processing_system7_vip_v1_0_4 -L xil_defaultlib -L xilinx_vip -work axi_vip_v1_1_2 "C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/board_param.v" "C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/global_param.v" "+incdir+../../../../clonicus/zynq/ipshared/ec67/hdl" "+incdir+../../../../clonicus/zynq/ipshared/02c8/hdl/verilog" "+incdir+../../../../clonicus/zynq/ipshared/b193/hdl" "+incdir+../../../../../../src/hdl/sub/dsp/verilog" "+incdir+../../../../../../src/hdl/sub/acquisition/verilog_sv" "+incdir+../../../../../../src/hdl/sub/interfaces" "+incdir+../../../../../../src/hdl/sub/correlator_new/verilog" "+incdir+../../../../../../src/hdl/sub/debug/verilog_sv" "+incdir+../../../../../../src/hdl/sub/dsp/verilog_sv" "+incdir+../../../../../../src/hdl/sub/imitator/verilog" "+incdir+../../../../../../src/hdl/trcv" "+incdir+../../../../../../src/hdl/sub/uart/rtl" "+incdir+D:/Xlinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../clonicus/zynq/ipshared/725c/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_2 -L axi_vip_v1_1_2 -L processing_system7_vip_v1_0_4 -L xil_defaultlib -L xilinx_vip -work processing_system7_vip_v1_0_4 "C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/board_param.v" "C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/global_param.v" "+incdir+../../../../clonicus/zynq/ipshared/ec67/hdl" "+incdir+../../../../clonicus/zynq/ipshared/02c8/hdl/verilog" "+incdir+../../../../clonicus/zynq/ipshared/b193/hdl" "+incdir+../../../../../../src/hdl/sub/dsp/verilog" "+incdir+../../../../../../src/hdl/sub/acquisition/verilog_sv" "+incdir+../../../../../../src/hdl/sub/interfaces" "+incdir+../../../../../../src/hdl/sub/correlator_new/verilog" "+incdir+../../../../../../src/hdl/sub/debug/verilog_sv" "+incdir+../../../../../../src/hdl/sub/dsp/verilog_sv" "+incdir+../../../../../../src/hdl/sub/imitator/verilog" "+incdir+../../../../../../src/hdl/trcv" "+incdir+../../../../../../src/hdl/sub/uart/rtl" "+incdir+D:/Xlinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../clonicus/zynq/ipshared/b193/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -64 -incr -work xil_defaultlib "C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/board_param.v" "C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/global_param.v" "+incdir+../../../../clonicus/zynq/ipshared/ec67/hdl" "+incdir+../../../../clonicus/zynq/ipshared/02c8/hdl/verilog" "+incdir+../../../../clonicus/zynq/ipshared/b193/hdl" "+incdir+../../../../../../src/hdl/sub/dsp/verilog" "+incdir+../../../../../../src/hdl/sub/acquisition/verilog_sv" "+incdir+../../../../../../src/hdl/sub/interfaces" "+incdir+../../../../../../src/hdl/sub/correlator_new/verilog" "+incdir+../../../../../../src/hdl/sub/debug/verilog_sv" "+incdir+../../../../../../src/hdl/sub/dsp/verilog_sv" "+incdir+../../../../../../src/hdl/sub/imitator/verilog" "+incdir+../../../../../../src/hdl/trcv" "+incdir+../../../../../../src/hdl/sub/uart/rtl" "+incdir+D:/Xlinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../cometicus.ip_user_files/bd/zynq/ip/zynq_processing_system7_0_0_0/sim/zynq_processing_system7_0_0_0.v" \
"../../../../cometicus.ip_user_files/bd/zynq/sim/zynq.v" \
"../../../../../../src/hdl/sub/debug/verilog/bram_block_v2.v" \
"../../../../../../src/hdl/sub/debug/verilog/bram_lut_v2.v" \
"../../../../../../src/hdl/sub/dsp/verilog/piped_adder/piped_adder.v" \
"../../../../../../src/hdl/sub/dsp/verilog/piped_adder/piped_adder_stage.v" \

vlog -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_2 -L axi_vip_v1_1_2 -L processing_system7_vip_v1_0_4 -L xil_defaultlib -L xilinx_vip -work xil_defaultlib "C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/board_param.v" "C:/Users/User/Desktop/misc-main/cometicus/src/hdl/misc/global_param.v" "+incdir+../../../../clonicus/zynq/ipshared/ec67/hdl" "+incdir+../../../../clonicus/zynq/ipshared/02c8/hdl/verilog" "+incdir+../../../../clonicus/zynq/ipshared/b193/hdl" "+incdir+../../../../../../src/hdl/sub/dsp/verilog" "+incdir+../../../../../../src/hdl/sub/acquisition/verilog_sv" "+incdir+../../../../../../src/hdl/sub/interfaces" "+incdir+../../../../../../src/hdl/sub/correlator_new/verilog" "+incdir+../../../../../../src/hdl/sub/debug/verilog_sv" "+incdir+../../../../../../src/hdl/sub/dsp/verilog_sv" "+incdir+../../../../../../src/hdl/sub/imitator/verilog" "+incdir+../../../../../../src/hdl/trcv" "+incdir+../../../../../../src/hdl/sub/uart/rtl" "+incdir+D:/Xlinx/Vivado/2018.1/data/xilinx_vip/include" \
"../../../../../../src/hdl/sub/acquisition/verilog_sv/DDS_bin.sv" \
"../../../../../../src/hdl/sub/acquisition/verilog_sv/DDS_sin_cos.sv" \
"../../../../../../src/hdl/sub/acquisition/verilog_sv/acq_IP.sv" \
"../../../../../../src/hdl/sub/interfaces/adc_interf.sv" \
"../../../../../../src/hdl/sub/interfaces/arm_interface.sv" \
"../../../../../../src/hdl/sub/acquisition/verilog_sv/arr_accum.sv" \
"../../../../../../src/hdl/sub/interfaces/axi3_interface.sv" \
"../../../../../../src/hdl/sub/interfaces/axi3_to_inter.sv" \
"../../../../../../src/hdl/sub/acquisition/verilog_sv/bram_controller.sv" \
"../../../../../../src/hdl/sub/correlator_new/verilog/ch_mul.sv" \
"../../../../../../src/hdl/sub/correlator_new/verilog/ch_mul_rom.sv" \
"../../../../../../src/hdl/sub/sync/verilog/conv_reg.sv" \
"../../../../../../src/hdl/sub/acquisition/verilog_sv/core.sv" \
"../../../../../../src/hdl/sub/correlator_new/verilog/corr_ch.sv" \
"../../../../../../src/hdl/misc/cpu_top.sv" \
"../../../../../../src/hdl/sub/debug/verilog_sv/data_collector.sv" \
"../../../../../../src/hdl/sub/sync/verilog/data_sync.sv" \
"../../../../../../src/hdl/sub/dsp/verilog_sv/dds_iq_hd.sv" \
"../../../../../../src/hdl/misc/deserLTC217x.sv" \
"../../../../../../src/hdl/sub/interfaces/dma.sv" \
"../../../../../../src/hdl/sub/sync/verilog/ed_det.sv" \
"../../../../../../src/hdl/sub/acquisition/verilog_sv/facq_prn_gen.sv" \
"../../../../../../src/hdl/sub/acquisition/verilog_sv/facq_prn_ram.sv" \
"../../../../../../src/hdl/sub/dsp/verilog_sv/freq_counter.sv" \
"../../../../../../src/hdl/sub/acquisition/verilog_sv/freq_shift.sv" \
"../../../../../../src/hdl/sub/acquisition/verilog_sv/fsm_controller.sv" \
"../../../../../../src/hdl/sub/interfaces/imi_interf.sv" \
"../../../../../../src/hdl/sub/imitator/verilog/imitator.sv" \
"../../../../../../src/hdl/sub/imitator/verilog/imitator_channel.sv" \
"../../../../../../src/hdl/sub/interfaces/intbus_interf.sv" \
"../../../../../../src/hdl/sub/correlator_new/verilog/irq_ctrl.sv" \
"../../../../../../src/hdl/sub/sync/verilog/latency.sv" \
"../../../../../../src/hdl/sub/sync/verilog/level_sync.sv" \
"../../../../../../src/hdl/sub/dsp/verilog_sv/lim_cntr.sv" \
"../../../../../../src/hdl/sub/dsp/verilog_sv/lim_qnt.sv" \
"../../../../../../src/hdl/sub/acquisition/verilog_sv/max_args.sv" \
"../../../../../../src/hdl/sub/dsp/verilog_sv/max_parallel.sv" \
"../../../../../../src/hdl/sub/acquisition/verilog_sv/mf.sv" \
"../../../../../../src/hdl/sub/dsp/verilog_sv/normalizer.sv" \
"../../../../../../src/hdl/sub/acquisition/verilog_sv/prestore.sv" \
"../../../../../../src/hdl/sub/correlator_new/verilog/prn_gen.sv" \
"../../../../../../src/hdl/sub/correlator_new/verilog/prn_ram.sv" \
"../../../../../../src/hdl/sub/acquisition/verilog_sv/quad.sv" \
"../../../../../../src/hdl/sub/debug/verilog_sv/ram_block_sp.sv" \
"../../../../../../src/hdl/sub/dsp/verilog/randn/randn.sv" \
"../../../../../../src/hdl/sub/dsp/verilog/randn/randn_u.sv" \
"../../../../../../src/hdl/sub/interfaces/regs_file.sv" \
"../../../../../../src/hdl/sub/sync/verilog/reset_sync.sv" \
"../../../../../../src/hdl/sub/debug/verilog_sv/rgb.sv" \
"../../../../../../src/hdl/sub/dsp/verilog_sv/sig_mag_v3.sv" \
"../../../../../../src/hdl/sub/sync/verilog/signal_sync.sv" \
"../../../../../../src/hdl/sub/correlator_new/verilog/time_scale_ch.sv" \
"../../../../../../src/hdl/sub/correlator_new/verilog/time_scale_com.sv" \
"../../../../../../src/hdl/trcv/trcv.sv" \
"../../../../../../src/hdl/sub/dsp/verilog_sv/vitdec.sv" \
"../../../../../../src/hdl/sub/imitator/verilog/wiper.sv" \
"../../../../../../src/hdl/cometicus.sv" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

