######################################################################
#
# File name : tb_compile.do
# Created on: Mon Mar 04 13:56:07 +0300 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xilinx_vip
vlib questa_lib/msim/xil_defaultlib

vmap xilinx_vip questa_lib/msim/xilinx_vip
vmap xil_defaultlib questa_lib/msim/xil_defaultlib

vlog -64 -incr -sv -L xil_defaultlib -work xilinx_vip "C:/Users/User/Desktop/misc-main/ibisARC/src/hdl/misc/board_param.v" "C:/Users/User/Desktop/misc-main/ibisARC/src/hdl/misc/global_param.v" \
"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -64 -incr -sv -L xil_defaultlib -work xil_defaultlib "C:/Users/User/Desktop/misc-main/ibisARC/src/hdl/misc/board_param.v" "C:/Users/User/Desktop/misc-main/ibisARC/src/hdl/misc/global_param.v" "+incdir+../hdl/misc" "+incdir+../hdl/sub/dsp/verilog" "+incdir+../hdl/sub/acquisition/verilog_sv" "+incdir+../hdl/sub/interfaces" "+incdir+../hdl/sub/correlator_new/verilog" "+incdir+../hdl/sub/debug/verilog_sv" "+incdir+../hdl/sub/dsp/verilog_sv" "+incdir+../hdl/sub/imitator/verilog"  "+incdir+../hdl/sub/uart/rtl" \
"../hdl/sub/interfaces/axi3_interface.sv" \

vlog -64 -incr -work xil_defaultlib "C:/Users/User/Desktop/misc-main/ibisARC/src/hdl/misc/board_param.v" "C:/Users/User/Desktop/misc-main/ibisARC/src/hdl/misc/global_param.v" "+incdir+../hdl/misc" "+incdir+../hdl/sub/dsp/verilog" "+incdir+../hdl/sub/acquisition/verilog_sv" "+incdir+../hdl/sub/interfaces" "+incdir+../hdl/sub/correlator_new/verilog" "+incdir+../hdl/sub/debug/verilog_sv" "+incdir+../hdl/sub/dsp/verilog_sv" "+incdir+../hdl/sub/imitator/verilog" "+incdir+../hdl/sub/uart/rtl" \
"../hdl/sub/debug/verilog/bram_block_v2.v" \
"../hdl/sub/debug/verilog/bram_lut_v2.v" \
"../hdl/sub/dsp/verilog/piped_adder/piped_adder.v" \
"../hdl/sub/dsp/verilog/piped_adder/piped_adder_stage.v" \

vlog -64 -incr -sv -L xil_defaultlib -work xil_defaultlib "C:/Users/User/Desktop/misc-main/ibisARC/src/hdl/misc/board_param.v" "C:/Users/User/Desktop/misc-main/ibisARC/src/hdl/misc/global_param.v" "+incdir+../hdl/misc" "+incdir+../hdl/sub/dsp/verilog" "+incdir+../hdl/sub/acquisition/verilog_sv" "+incdir+../hdl/sub/interfaces" "+incdir+../hdl/sub/correlator_new/verilog" "+incdir+../hdl/sub/debug/verilog_sv" "+incdir+../hdl/sub/dsp/verilog_sv" "+incdir+../hdl/sub/imitator/verilog"  "+incdir+../hdl/sub/uart/rtl" \
"../hdl/sub/acquisition/verilog_sv/DDS_bin.sv" \
"../hdl/sub/acquisition/verilog_sv/DDS_sin_cos.sv" \
"../hdl/sub/acquisition/verilog_sv/acq_IP.sv" \
"../hdl/sub/interfaces/adc_interf.sv" \
"../hdl/sub/acquisition/verilog_sv/arr_accum.sv" \
"../hdl/sub/interfaces/axi3_to_inter.sv" \
"../hdl/sub/acquisition/verilog_sv/bram_controller.sv" \
"../hdl/sub/correlator_new/verilog/ch_mul.sv" \
"../hdl/sub/correlator_new/verilog/ch_mul_rom.sv" \
"../hdl/sub/sync/verilog/conv_reg.sv" \
"../hdl/sub/acquisition/verilog_sv/core.sv" \
"../hdl/sub/correlator_new/verilog/corr_ch.sv" \
"../hdl/sub/debug/verilog_sv/data_collector.sv" \
"../hdl/sub/sync/verilog/data_sync.sv" \
"../hdl/sub/dsp/verilog_sv/dds_iq_hd.sv" \
"../hdl/sub/sync/verilog/ed_det.sv" \
"../hdl/sub/acquisition/verilog_sv/facq_prn_gen.sv" \
"../hdl/sub/acquisition/verilog_sv/facq_prn_ram.sv" \
"../hdl/sub/dsp/verilog_sv/freq_counter.sv" \
"../hdl/sub/acquisition/verilog_sv/freq_shift.sv" \
"../hdl/sub/acquisition/verilog_sv/fsm_controller.sv" \
"../hdl/ibisARC.sv" \
"../hdl/sub/interfaces/imi_interf.sv" \
"../hdl/sub/imitator/verilog/imitator.sv" \
"../hdl/sub/imitator/verilog/imitator_channel.sv" \
"../hdl/sub/interfaces/intbus_interf.sv" \
"../hdl/sub/correlator_new/verilog/irq_ctrl.sv" \
"../hdl/sub/sync/verilog/latency.sv" \
"../hdl/sub/sync/verilog/level_sync.sv" \
"../hdl/sub/dsp/verilog_sv/lim_cntr.sv" \
"../hdl/sub/dsp/verilog_sv/lim_qnt.sv" \
"../hdl/sub/acquisition/verilog_sv/max_args.sv" \
"../hdl/sub/dsp/verilog_sv/max_parallel.sv" \
"../hdl/sub/acquisition/verilog_sv/mf.sv" \
"../hdl/sub/dsp/verilog_sv/normalizer.sv" \
"../hdl/sub/acquisition/verilog_sv/prestore.sv" \
"../hdl/sub/correlator_new/verilog/prn_gen.sv" \
"../hdl/sub/correlator_new/verilog/prn_ram.sv" \
"../hdl/sub/acquisition/verilog_sv/quad.sv" \
"../hdl/sub/debug/verilog_sv/ram_block_sp.sv" \
"../hdl/sub/dsp/verilog/randn/randn.sv" \
"../hdl/sub/dsp/verilog/randn/randn_u.sv" \
"../hdl/sub/interfaces/regs_file.sv" \
"../hdl/sub/sync/verilog/reset_sync.sv" \
"../hdl/sub/dsp/verilog_sv/sig_mag_v3.sv" \
"../hdl/sub/sync/verilog/signal_sync.sv" \
"../hdl/sub/correlator_new/verilog/time_scale_ch.sv" \
"../hdl/sub/correlator_new/verilog/time_scale_com.sv" \
"../hdl/trcv/trcv.sv" \
"../hdl/sub/dsp/verilog_sv/vitdec.sv" \
"../hdl/sub/imitator/verilog/wiper.sv" \
"../../../../../../src/tb/tb.sv" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

