TEST=BeamFormer \
     BeamFormer_n \
     cov_matrix \
     fir_filter \
     kix_filter_n \
     multi_sum_n \
     NFBF_wrapper \
     NullFormer \
     NullFormer_n \
     piped_adder

all:

clean:
	for i in $(TEST); do \
	    make -C $$i clean; \
        done


