`define BOC_REG_WIDTH               8 

`define CHANNEL_CONFIG_OFFSET       BASE_ADDR + `ADDR_WIDTH'h00
`define CHANNEL_CONFIG2_OFFSET      BASE_ADDR + `ADDR_WIDTH'h01
`define CODE_DOINIT_OFFSET          BASE_ADDR + `ADDR_WIDTH'h02

`define CODE_STATE1_OFFSET          BASE_ADDR + `ADDR_WIDTH'h04
`define CODE_BITMASK1_OFFSET        BASE_ADDR + `ADDR_WIDTH'h05
`define CODE_OUT_BITMASK1_OFFSET    BASE_ADDR + `ADDR_WIDTH'h06
`define CODE_STATE2_OFFSET          BASE_ADDR + `ADDR_WIDTH'h07
`define CODE_BITMASK2_OFFSET        BASE_ADDR + `ADDR_WIDTH'h08
`define CODE_OUT_BITMASK2_OFFSET    BASE_ADDR + `ADDR_WIDTH'h09
`define PRN_LENGTH_OFFSET           BASE_ADDR + `ADDR_WIDTH'h0A
`define PRN_INIT_OFFSET             BASE_ADDR + `ADDR_WIDTH'h0B
`define PRN_LENGTH1_OFFSET          BASE_ADDR + `ADDR_WIDTH'h0C
`define PRN_INIT1_OFFSET            BASE_ADDR + `ADDR_WIDTH'h0D
`define BOC_REGS_OFFSET             BASE_ADDR + `ADDR_WIDTH'h0E


`define CODE_PHASE_INIT_OFFSET      BASE_ADDR + `ADDR_WIDTH'h10
`define CODE_PHASE_OFFSET           BASE_ADDR + `ADDR_WIDTH'h10

`define CHIP_AND_SYMB_INIT_OFFSET   BASE_ADDR + `ADDR_WIDTH'h11
`define CHIP_AND_SYMB_OFFSET        BASE_ADDR + `ADDR_WIDTH'h11

`define EPOCH_AND_TOW_INIT_OFFSET   BASE_ADDR + `ADDR_WIDTH'h12
`define EPOCH_AND_TOW_OFFSET        BASE_ADDR + `ADDR_WIDTH'h12

`define CHIP_MAX_OFFSET             BASE_ADDR + `ADDR_WIDTH'h13

`define EPOCH_AND_SYMB_MAX_OFFSET   BASE_ADDR + `ADDR_WIDTH'h14

`define EPOCH_INTR_OFFSET           BASE_ADDR + `ADDR_WIDTH'h15
  
`define CODE_RATE_OFFSET            BASE_ADDR + `ADDR_WIDTH'h16


`define PHASE_RATE_OFFSET           BASE_ADDR + `ADDR_WIDTH'h18
`define PHASE_OFFSET                BASE_ADDR + `ADDR_WIDTH'h19
`define PHASE_CYCLES_OFFSET         BASE_ADDR + `ADDR_WIDTH'h1A
`define IPQP_OFFSET                 BASE_ADDR + `ADDR_WIDTH'h1C 
`define IE1QE1_OFFSET               BASE_ADDR + `ADDR_WIDTH'h1D 
`define IL1QL1_OFFSET               BASE_ADDR + `ADDR_WIDTH'h1E 
`define IE2QE2_OFFSET               BASE_ADDR + `ADDR_WIDTH'h1F 
`define IL2QL2_OFFSET               BASE_ADDR + `ADDR_WIDTH'h20


//`define CHANNEL_CONFIG2_OFFSET      BASE_ADDR + `ADDR_WIDTH'h24